### ISSUE TITLE
[UI/UX] CSS styling tweaks

### ISSUE THREAD

**Issue by BenSchZA** [datagemsai/ChartGPT-API#11]
## Tasks

- [ ] On mobile, dropdown list elements overlap (text wrapping, CSS delimiters to more clearly show distinction between questions)
- [ ] On both desktop and mobile list elements don't have text wrapping
<img width="742" alt="image" src="https://user-images.githubusercontent.com/13078998/236825892-ea57dd73-8647-423e-ba19-b3f3c360f017.png">

- [x] Set base theme to light until we have a logo that works for both: https://docs.streamlit.io/library/advanced-features/theming

## Resources
https://discuss.streamlit.io/t/css-hacks/14501
